### ISSUE TITLE
`forge fmt` does not always respect project's Foundry config

### ISSUE THREAD

**Issue by PaulRBerg** [NomicFoundation/hardhat-vscode#456]
I keep bumping into the bug that should have been fixed by https://github.com/NomicFoundation/hardhat-vscode/pull/316.

Hardhat VSCode does not always pick up my `[fmt]` configuration in `foundry.toml`:

```toml
[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
```

In particular, it does not consistently follow the `bracket_spacing` rule, e.g. this:

```solidity
import { IPRBProxy } from "../../src/interfaces/IPRBProxy.sol";
```

Turns into this:

```solidity
import {IPRBProxy} from "../../src/interfaces/IPRBProxy.sol";
```

The bug is transitory, though. When I open the file again and save it, the fmt rules are picked up correctly,

I cannot pinpoint the root cause, but this happens very often - basically every day. Might there be a race condition somewhere in Hardhat VSCode?

For context, these are my VSCode settings:

```json
{
  "[solidity]": {
    "editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
  },
  "[toml]": {
    "editor.defaultFormatter": "tamasfe.even-better-toml"
  },
  "npm.exclude": "**/lib/**",
  "solidity.formatter": "forge"
}
```

This happens in all of my repos, but for a particular example, you can take a look at [PRBProxy](https://github.com/PaulRBerg/prb-proxy).
