### ISSUE TITLE
Problem with imports on Ape Project

### ISSUE THREAD

**Issue by meatballs** [NomicFoundation/hardhat-vscode#516]
When I use dependencies and import remapping within an Ape project, I get "File not found" errors reported in my import statements.

As per the [Ape dependencies docs](https://docs.apeworx.io/ape/stable/userguides/dependencies.html), I have the following in my `ape-config.yaml`:
```
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.3

solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.9.3"
```

Then, within a solidity file:
```sol
import "@openzeppelin/token/ERC721/ERC721.sol";
```
If I run `ape compile`, everything is happy and my contract compiles ok

But, in my editor (neovim), the language server gives:
```
Source "@openzeppelin/token/ERC721/ERC721.sol" not found: File not found. Searched the following locations: "". solidity (6275) [5, 1]
```
